import { useState } from "react";
import type { Brief } from "../../pages/App";
import api from "../../lib/api";
import Loader from "../ui/Loader";
import Button from "../ui/Button";

interface BlueprintDialogProps {
  brief: Brief;
  onClose: () => void;
  onExplanationGenerated: (explanation: string) => void;
}

const SECTIONS = [
  "THE VISION",
  "THE PROBLEM",
  "THE SOLUTION",
  "HOW IT WORKS",
  "WHO IT'S FOR",
  "THE OPPORTUNITY",
  "WHAT COULD GO WRONG",
  "THE FIRST 30 DAYS",
];

const parseExplanation = (
  text: string,
): { heading: string; content: string }[] => {
  const sections: { heading: string; content: string }[] = [];

  SECTIONS.forEach((heading, i) => {
    const current = text.indexOf(heading);
    if (current === -1) return;
    const next = SECTIONS.slice(i + 1).reduce((acc, h) => {
      const idx = text.indexOf(h);
      return idx !== -1 && idx < acc ? idx : acc;
    }, text.length);
    const content = text.slice(current + heading.length, next).trim();
    sections.push({ heading, content });
  });

  return sections;
};

const formatAsText = (brief: Brief, explanation: string): string =>
  `
BLUEPRINT — ${brief.title.toUpperCase()}
Generated by DevBrief
${"─".repeat(50)}

${explanation}

${"─".repeat(50)}
devbrief.app
`.trim();

export default function BlueprintDialog({
  brief,
  onClose,
  onExplanationGenerated,
}: BlueprintDialogProps) {
  const [explanation, setExplanation] = useState<string | null>(
    brief.explanation || null,
  );
  const [loading, setLoading] = useState(!brief.explanation);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Auto-generate on mount if no cached explanation
  const generate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.post(`/app/brief/${brief.id}/explain`);
      setExplanation(res.data.explanation);
      onExplanationGenerated(res.data.explanation);
    } catch (err: any) {
      setError(err.response?.data?.message || "Failed to generate Blueprint");
    } finally {
      setLoading(false);
    }
  };

  // Auto trigger on mount
  useState(() => {
    if (!brief.explanation) generate();
  });

  const handleDownload = () => {
    if (!explanation) return;
    const blob = new Blob([formatAsText(brief, explanation)], {
      type: "text/plain",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `blueprint-${brief.title.toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    if (!explanation) return;
    await navigator.clipboard.writeText(formatAsText(brief, explanation));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const sections = explanation ? parseExplanation(explanation) : [];

  return (
    <>
      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; }
          to   { opacity: 1; }
        }
        @keyframes slideUp {
          from { opacity: 0; transform: translateY(24px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .blueprint-scroll::-webkit-scrollbar { width: 4px; }
        .blueprint-scroll::-webkit-scrollbar-track { background: transparent; }
        .blueprint-scroll::-webkit-scrollbar-thumb { background: #ffffff15; border-radius: 4px; }
        .blueprint-scroll { scrollbar-width: thin; scrollbar-color: #ffffff15 transparent; }
      `}</style>

      {/* Backdrop */}
      <div
        onClick={onClose}
        style={{
          position: "fixed",
          inset: 0,
          background: "#000000cc",
          backdropFilter: "blur(6px)",
          zIndex: 50,
          animation: "fadeIn 0.2s ease",
        }}
      />

      {/* Dialog */}
      <div
        style={{
          position: "fixed",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          width: "90%",
          maxWidth: "680px",
          maxHeight: "85vh",
          background: "#111111",
          border: "1px solid #ffffff15",
          borderRadius: "16px",
          zIndex: 51,
          display: "flex",
          flexDirection: "column",
          animation: "slideUp 0.25s ease",
          overflow: "hidden",
        }}
      >
        {/* Header */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "1.25rem 1.5rem",
            borderBottom: "1px solid #ffffff0f",
            flexShrink: 0,
          }}
        >
          <div>
            <div
              style={{
                fontFamily: "'DM Mono', monospace",
                fontSize: "0.7rem",
                color: "#CBFF5E60",
                letterSpacing: "0.06em",
                marginBottom: "0.3rem",
              }}
            >
              BLUEPRINT
            </div>
            <div
              style={{
                fontFamily: "'Syne', sans-serif",
                fontSize: "1.05rem",
                fontWeight: 800,
                color: "#ffffff",
                letterSpacing: "-0.02em",
              }}
            >
              {brief.title}
            </div>
          </div>

          {/* Actions */}
          <div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
            {explanation && (
              <>
                <button
                  onClick={handleCopy}
                  style={{
                    background: "transparent",
                    border: "1px solid #ffffff15",
                    borderRadius: "6px",
                    padding: "0.45rem 0.9rem",
                    fontFamily: "'DM Sans', sans-serif",
                    fontSize: "0.8rem",
                    color: copied ? "#CBFF5E" : "#ffffff50",
                    cursor: "pointer",
                    transition: "all 0.2s",
                    borderColor: copied ? "#CBFF5E40" : "#ffffff15",
                  }}
                >
                  {copied ? "✓ Copied" : "Copy"}
                </button>
                <button
                  onClick={handleDownload}
                  style={{
                    background: "#CBFF5E",
                    border: "none",
                    borderRadius: "6px",
                    padding: "0.45rem 0.9rem",
                    fontFamily: "'DM Sans', sans-serif",
                    fontSize: "0.8rem",
                    fontWeight: 500,
                    color: "#080808",
                    cursor: "pointer",
                    transition: "opacity 0.2s",
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.opacity = "0.85")}
                  onMouseLeave={(e) => (e.currentTarget.style.opacity = "1")}
                >
                  Download .txt
                </button>
              </>
            )}
            <button
              onClick={onClose}
              style={{
                background: "transparent",
                border: "1px solid #ffffff15",
                borderRadius: "6px",
                padding: "0.45rem 0.6rem",
                color: "#ffffff40",
                cursor: "pointer",
                fontSize: "1rem",
                lineHeight: 1,
                transition: "all 0.2s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.color = "#ffffff")}
              onMouseLeave={(e) => (e.currentTarget.style.color = "#ffffff40")}
            >
              ✕
            </button>
          </div>
        </div>

        {/* Content */}
        <div
          className="blueprint-scroll"
          style={{
            flex: 1,
            overflowY: "auto",
            padding: "1.5rem",
          }}
        >
          {/* Loading */}
          {loading && (
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                padding: "4rem 0",
                gap: "1rem",
              }}
            >
              <Loader label="Writing your Blueprint..." />
              <div
                style={{
                  fontFamily: "'DM Sans', sans-serif",
                  fontSize: "0.82rem",
                  color: "#ffffff25",
                  textAlign: "center",
                  maxWidth: "280px",
                  lineHeight: 1.6,
                }}
              >
                This takes about 10 seconds — we're crafting a full vision
                document for your idea.
              </div>
            </div>
          )}

          {/* Error */}
          {error && !loading && (
            <div
              style={{
                textAlign: "center",
                padding: "3rem 0",
              }}
            >
              <div
                style={{
                  fontFamily: "'DM Sans', sans-serif",
                  fontSize: "0.9rem",
                  color: "#ff5f56",
                  marginBottom: "1.25rem",
                }}
              >
                {error}
              </div>
              <Button size="sm" variant="secondary" onClick={generate}>
                Try again
              </Button>
            </div>
          )}

          {/* Sections */}
          {!loading && !error && sections.length > 0 && (
            <div
              style={{ display: "flex", flexDirection: "column", gap: "2rem" }}
            >
              {sections.map((section, i) => (
                <div key={i}>
                  <div
                    style={{
                      fontFamily: "'DM Mono', monospace",
                      fontSize: "0.7rem",
                      color: "#CBFF5E",
                      letterSpacing: "0.06em",
                      marginBottom: "0.6rem",
                    }}
                  >
                    {section.heading}
                  </div>
                  <p
                    style={{
                      fontFamily: "'DM Sans', sans-serif",
                      fontSize: "0.92rem",
                      color: "#ffffff70",
                      lineHeight: 1.75,
                      fontWeight: 300,
                      margin: 0,
                    }}
                  >
                    {section.content}
                  </p>
                </div>
              ))}

              {/* Cached indicator */}
              {brief.explanation && (
                <div
                  style={{
                    fontFamily: "'DM Mono', monospace",
                    fontSize: "0.68rem",
                    color: "#ffffff20",
                    textAlign: "center",
                    paddingTop: "1rem",
                    borderTop: "1px solid #ffffff08",
                  }}
                >
                  Blueprint retrieved from cache
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </>
  );
}
