import { useEffect, useRef, useState } from "react";
import type { Brief } from "../../pages/App";
import Toast from "../ui/Toast";

interface ExportMenuProps {
  brief: Brief;
}

const formatAsText = (brief: Brief): string =>
  `
DEVBRIEF — ${brief.title.toUpperCase()}
Generated: ${new Date(brief.created_at).toLocaleDateString()}
${"─".repeat(50)}

YOUR IDEA
${brief.idea}

TIMELINE
${brief.timeline}

CORE FEATURES
${brief.features.map((f, i) => `${String(i + 1).padStart(2, "0")}. ${f}`).join("\n")}

SUGGESTED STACK
${brief.stack.join(", ")}

QUESTIONS TO ASK YOUR DEVELOPER
${brief.questions.map((q, i) => `${String(i + 1).padStart(2, "0")}. ${q}`).join("\n")}

${"─".repeat(50)}
Generated by DevBrief — devbrief.app
`.trim();

export default function ExportMenu({ brief }: ExportMenuProps) {
  const [open, setOpen] = useState(false);
  const [toast, setToast] = useState<{
    message: string;
    type: "success" | "error";
  } | null>(null);
  const [isMobile, setIsMobile] = useState(false);
  const triggerRef = useRef<HTMLButtonElement | null>(null);

  useEffect(() => {
    const update = () => setIsMobile(window.innerWidth <= 480);
    update();
    window.addEventListener("resize", update);
    return () => window.removeEventListener("resize", update);
  }, []);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatAsText(brief));
      setToast({ message: "Brief copied to clipboard", type: "success" });
      setOpen(false);
    } catch {
      setToast({ message: "Failed to copy", type: "error" });
    }
  };

  const handleDownload = () => {
    const blob = new Blob([formatAsText(brief)], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `devbrief-${brief.title.toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setOpen(false);
    setToast({ message: "Brief downloaded", type: "success" });
  };

  const handleCopyJSON = async () => {
    try {
      await navigator.clipboard.writeText(JSON.stringify(brief, null, 2));
      setToast({ message: "JSON copied to clipboard", type: "success" });
      setOpen(false);
    } catch {
      setToast({ message: "Failed to copy", type: "error" });
    }
  };

  return (
    <>
      <div style={{ position: "relative" }}>
        {/* Trigger */}
        <button
          ref={triggerRef}
          onClick={() => setOpen((prev) => !prev)}
          style={{
            display: "flex",
            alignItems: "center",
            gap: "0.4rem",
            background: "transparent",
            border: "1px solid #ffffff15",
            borderRadius: "8px",
            padding: "0.55rem 1rem",
            fontFamily: "'DM Sans', sans-serif",
            fontSize: "0.85rem",
            color: "#ffffff50",
            cursor: "pointer",
            transition: "all 0.2s ease",
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = "#ffffff30";
            e.currentTarget.style.color = "#ffffff";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = "#ffffff15";
            e.currentTarget.style.color = "#ffffff50";
          }}
        >
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
            <path
              d="M9 2H5a1 1 0 00-1 1v8a1 1 0 001 1h4a1 1 0 001-1V3a1 1 0 00-1-1z"
              stroke="currentColor"
              strokeWidth="1.2"
            />
            <path
              d="M9 2v3h3M9 2l3 3"
              stroke="currentColor"
              strokeWidth="1.2"
              strokeLinecap="round"
            />
          </svg>
          Export
          <svg
            width="10"
            height="10"
            viewBox="0 0 10 10"
            fill="none"
            style={{
              transform: open ? "rotate(180deg)" : "none",
              transition: "transform 0.2s",
            }}
          >
            <path
              d="M2 3.5l3 3 3-3"
              stroke="currentColor"
              strokeWidth="1.2"
              strokeLinecap="round"
            />
          </svg>
        </button>

        {/* Dropdown */}
        {open && (
          <>
            {/* Backdrop */}
            <div
              style={{ position: "fixed", inset: 0, zIndex: 9 }}
              onClick={() => setOpen(false)}
            />
            <div
              style={{
                position: isMobile ? "fixed" : "absolute",
                ...(isMobile
                  ? {
                      left: 12,
                      right: 12,
                      bottom: 12,
                      borderRadius: 12,
                    }
                  : { top: "calc(100% + 6px)", right: 0 }),
                background: "#1a1a1a",
                border: "1px solid #ffffff15",
                padding: "0.4rem",
                zIndex: 10,
                minWidth: isMobile ? undefined : "180px",
                boxShadow: "0 8px 32px #00000060",
                maxHeight: isMobile ? "60vh" : "none",
                overflow: isMobile ? "auto" : "visible",
              }}
            >
              {[
                { label: "Copy as text", icon: "📋", action: handleCopy },
                { label: "Download .txt", icon: "⬇️", action: handleDownload },
                { label: "Copy as JSON", icon: "{ }", action: handleCopyJSON },
              ].map((item) => (
                <button
                  key={item.label}
                  onClick={item.action}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "0.6rem",
                    width: "100%",
                    padding: "0.6rem 0.75rem",
                    background: "transparent",
                    border: "none",
                    borderRadius: "7px",
                    fontFamily: "'DM Sans', sans-serif",
                    fontSize: "0.85rem",
                    color: "#ffffff60",
                    cursor: "pointer",
                    textAlign: "left",
                    transition: "all 0.15s ease",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background = "#ffffff08";
                    e.currentTarget.style.color = "#ffffff";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background = "transparent";
                    e.currentTarget.style.color = "#ffffff60";
                  }}
                >
                  <span style={{ fontSize: "0.8rem", minWidth: "18px" }}>
                    {item.icon}
                  </span>
                  {item.label}
                </button>
              ))}
            </div>
          </>
        )}
      </div>

      {toast && (
        <Toast
          message={toast.message}
          type={toast.type}
          onClose={() => setToast(null)}
        />
      )}
    </>
  );
}
